course_app/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from course_app.views import (
    ListOfCourses,
    CreateUser,
    login_view,
    logout_view,
    Profile,
    EditProfileView,
    CourseByCategory,
    CancelView,
    SuccessView,
    DetailCourses,
    stripe_webhook,
    course_comments, mark_as_done_homework,
)

urlpatterns = [
    path("", ListOfCourses.as_view(), name="home-page"),
    path("register/", CreateUser.as_view(), name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("profile/<int:pk>/", Profile.as_view(), name="profile"),
    path("cancel/", CancelView.as_view(), name="cancel"),
    # path("success/", SuccessView.as_view(), name="success"),
    path("profile/edit/<int:pk>/", EditProfileView.as_view(), name="profile-edit"),
    path("category/<int:pk>/", CourseByCategory.as_view(), name="category"),
    path("course/detail/<int:pk>/", DetailCourses.as_view(), name="detail-page"),
    path("webhook/", stripe_webhook),
    path("comments/<int:pk>/", course_comments, name="comments"),
    path("course/detail/<int:pk_course>/mark_as_done/<int:pk>/",mark_as_done_homework,name="mark_as_done")


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_name = "course"

course_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("course_app.urls", namespace="course")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
]

templates/course/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block css %}
        <link rel="stylesheet" href="{% static 'card_styles.css' %}">
    {% endblock %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
          integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <title>Title</title>

</head>
<style type="text/css">
    body {
        background: gainsboro !important;
    }

    /* Adding !important forces the browser to overwrite the default style applied by Bootstrap */
</style>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url "course:home-page" %}">SpaceAcademy</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarScroll"
            aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav mr-auto my-2 my-lg-0 navbar-nav-scroll" style="max-height: 100px;">
            <li class="nav-item active">
                <a class="nav-link" href="{% url "course:home-page" %}">Home <span class="sr-only">(current)</span></a>
            </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'course:profile' pk=user.pk %}">Profile</a>
            </li>
        {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
                    Categories
                </a>
                <ul class="dropdown-menu">
                    {% for category in categories %}
                        <li><a class="dropdown-item"
                               href="{% url "course:category" pk=category.pk %}">{{ category.title }}</a></li>
                    {% endfor %}
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link disabled">Link</a>
            </li>
        </ul>
        <form style="padding-right: 10px" class="d-flex">
            {% if user.is_authenticated %}
                <a style="padding-right: 10px" class="btn btn-danger" href="{% url "course:logout" %}" role="button">Logout</a>
            {% else %}
                <a class="btn btn-danger mr-sm-2" href="{% url "course:login" %}" role="button"> Login</a>
                <a class="btn btn-primary" href="{% url "course:register" %}" role="button">Register</a>
            {% endif %}
        </form>
    </div>
</nav>

{% block content %}
    <div class="container">
        <div class="row mx-auto">
            <div class="col-md3">
            </div>


            {% for course in course_list %}
                <div style="border-radius: 15px" class="custom-card">
                    <div class="custom-card-header">
                        <img style="width: border-box" src="{{ course.image.url }}" alt="image"/>
                    </div>
                    <div class="card-body">
                        <span class="tag tag-teal">{{ course.categories.title }}</span>
                        <h4>
                            {{ course.title }}
                        </h4>
                        <p style="font-family: 'Open Sans SemiBold',sans-serif">
                            {{ course.description }} <br>

                            Читают: {{ course.user_course.count }}


                        </p>
                      {% if course in user.course_paid.all %}

                        <a href="{% url "course:detail-page" pk=course.pk %}" class="btn btn-success">Читать</a>
                        {% else %}
                        <a href="{% url "course:detail-page" pk=course.pk %}" class="btn btn-primary">Подписаться</a>

                      {% endif %}
                      <a href="{% url "course:comments" pk=course.pk %}" class="btn btn-primary">Отзывы</a>
                    </div>
                </div>

            {% endfor %}
        </div>
    </div>
{% endblock %}


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
        crossorigin="anonymous"></script>
</body>
</html>

templates/course/cancel.html
Cancelled!

templates/course/categories.html
{% extends "course/base.html" %}
{% block content %}

    {% for course in course_list %}
        <div style="border-radius: 15px" class="custom-card">
            <div class="custom-card-header">
                <img style="width: border-box" src="{{ course.image.url }}" alt="image"/>
            </div>
            <div class="card-body">
                <span class="tag tag-teal">{{ course.categories.title }}</span>
                <h4>
                    {{ course.title }}
                </h4>
                <p style="font-family: 'Open Sans SemiBold',sans-serif">
                    {{ course.description }} <br>

                    Читают: {{ course.course.count }}


                </p>
                <a href="#" class="btn btn-primary">Подписаться</a>
            </div>
        </div>

    {% endfor %}
{% endblock %}

templates/course/comments.html
{% extends "course/base.html" %}
{% load static %}{% block css %}
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'comments.css' %}">
        {% endblock %}
{% block content %}
<section class="content-item" id="comments">
    <div class="container">
    	<div class="row">
      <div class="col-sm-1">
      </div>
            <div class="col-sm-10">
            <form method="post">
              {% if user.is_authenticated %}
                	<h3 class="pull-left">Add new comment!</h3>
                    <fieldset>
                        <div class="row">
                            <div class="col-sm-3 col-lg-2 hidden-xs">
                            	<img style="width: 100px;height: 100px;margin-top: 25px;border-radius: 15px;margin-left: 10px" class="img-responsive" src="{{ user.image.url }}" alt="">
                            </div>
                            <div class="form-group col-xs-12 col-sm-9 col-lg-10">
                                {% csrf_token %}
                              <label for="message"></label><textarea class="form-control" id="message" placeholder="Your message" required="" name="content"></textarea>
                                <input class="btn btn-success pull-right" type="submit" value="Add comment">
                            </div>
                        </div>
                    </fieldset>
                </form>
                    {% else %}
                    <h5 style="text-align: center">To see leave comments - login first</h5>
                <a style="margin-left: 430px" class="btn btn-success mr-sm-2" href="{% url "course:login" %}" role="button"> Login</a>

                  {% endif %}
                {% if comments %}
                  <h3>{{ comments.count }} Comments</h3>
                  {% else %}
                  <h3>There is no comments,become first!</h3>
                {% endif %}



                {% for comment in comments %}
                <!-- COMMENT 1 - START -->
                <div class="media">
                    <a class="pull-left" href="#"><img style=" border-radius: 15px" class="media-object" src="{{ comment.sender.image.url }}" alt=""></a>
                    <div class="media-body">
                        <h4 class="media-heading">
                          <a href="{% url "course:profile" pk=comment.sender.pk %}">{{ comment.sender}}</a></h4>
                      <p>{{ comment.content}}</p>
                        <ul class="list-unstyled list-inline media-detail pull-left">
                            <li><i class="fa fa-calendar"></i>{{ comment.created_at }}</li>
                        </ul>
                        <ul class="list-unstyled list-inline media-detail pull-right">
                        </ul>
                    </div>
                </div>
                <!-- COMMENT 1 - END -->
            {% endfor %}

            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/course/course_detail.html
{% extends "course/base.html" %}
{% load embed_video_tags %}
{% load static %}
{% block css %}
<link rel="stylesheet" href="{% static 'detail.css' %}">
{% endblock %}
{% block content %}
    <div class="container">
        <div class="row mx-auto">
            <div class="col-md3">
            </div>
            <div class="container-fluid">
                <div class="row">
                    <div class="col-10 offset-1">
                    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
                      <script src="https://js.stripe.com/v3/"></script>
                        <h2 style="text-align: center">{{ course.title }}</h2>
                        <br/>
                        {% if course in user.course_paid.all %}
                            {% for lecture in lectures %}
                                <details >
                                    <summary style="background-color: #F0F0F0;border-radius: 20px;margin-top: 5px">{{ lecture.title }}
                                      {% if lecture in user.listened_lecture.all %}
                                        <img style="float: right" height="25px" width="25px" src="{% static "success-icon.png" %}" alt="">
                                      {% elif lecture in user.rework_lecture.all %}
                                        <img style="float: right" height="25px" width="25px" src="{% static "628px-Achtung-yellow.svg.png" %}" alt="">
                                      {% endif %}

                                    </summary>
                                     <div style="float: left;padding:20px"> {% video lecture.video.video 'tiny' %}</div>

                                  <p style="text-align: justify;padding-top: 20px"> {{ lecture.text }}
                                  <br>
                                    Homework : {{ lecture.home_work }}
                                    <br></p>
                                  <form action="{% url "course:mark_as_done" pk_course=course.pk pk=lecture.pk %}" method="post">
                                    {% csrf_token %}

                                    {% if lecture in user.listened_lecture.all %}
                                        <button class="btn btn-danger" name="delete" value="unfollow">
                                            Repeat material
                                        </button>
                                    {% else %}
                                        <button class="btn btn-success" name="assign" value="follow">
                                            Done
                                        </button>
                                    {% endif %}
                                </form>


                                </details>
                            {% endfor %}
                        {% else %}
                          <details >
                                    <summary style="background-color: #F0F0F0;border-radius: 20px;margin-top: 5px">{{ lectures.first.title }}</summary>
                            <div style="float: left;padding:20px"> {% video lectures.first.video.video 'tiny' %}</div>
                                    <p style="text-align: justify;padding-top: 20px"> {{ lectures.first.text }}<br>Homework : {{ lectures.first.home_work |urlize}}</p>

                                </details>
                            <section>
                                <div class="product">
                                    <div class="description">
                                    </div>
                                </div>
                              <h5 style="text-align: center">To see more lectures please subscribe!</h5>
                                <button style="margin-left: 390px" class="btn btn-success mr-sm-2" type="button" id="checkout-button">Subscribe</button>
                            </section>
                            {% csrf_token %}
                            <script type="text/javascript">
                                const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
                                var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
                                var checkoutButton = document.getElementById("checkout-button");
                                checkoutButton.addEventListener("click", function () {
                                    fetch("{% url 'course:detail-page' product.id %}", {
                                        method: "POST",
                                        headers: {
                                            'X-CSRFToken': csrftoken
                                        }
                                    })
                                        .then(function (response) {
                                            return response.json();
                                        })
                                        .then(function (session) {
                                            return stripe.redirectToCheckout({sessionId: session.id});
                                        })
                                        .then(function (result) {
                                            if (result.error) {
                                                alert(result.error.message);
                                            }
                                        })
                                        .catch(function (error) {
                                            console.error("Error:", error);
                                        });
                                });
                            </script>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/course/logged_out.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/course/login.html
{% extends "course/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
            </div>
            <div class="col-sm">

                <form action="{% url "course:login" %}" method="post">
                    {% if errors %}
                        <h5 style="color: darkred;text-align: center;margin-top: 10px">{{ errors }}</h5>
                    {% endif %}
                    {% csrf_token %}
                    <div style="margin-top: 20px" class="form-group">
                        <label for="exampleInputEmail1">Login</label>
                        <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                               placeholder="Enter your login" name="username">
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Password</label>
                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"
                               name="password">
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col-sm">
            </div>
        </div>
    </div>


{% endblock %}

templates/course/payment.html
{% load static %}
<html lang="eu">
<head>
    <title>Buy cool new product</title>
    <link rel="stylesheet" href="{% static "profile.css" %}">
    <script src="https://polyfill.io/v3/polyfill.min.js?version=3.52.1&features=fetch"></script>
    <script src="https://js.stripe.com/v3/"></script>
    <style>
        * {
            box-sizing: border-box;
        }
    </style>
</head>
<body>
<section>
    <div class="product">
        <div class="description">
            <h3>{{ product.name }}</h3>
            <h5>${{ product.get_display_price }}</h5>
        </div>
    </div>
    <form action="" method="post">
        <button type="button" id="checkout-button">Checkout</button>
    </form>
</section>
{% csrf_token %}
</body>
<script type="text/javascript">
    const csrftoken = document.querySelector('[name=csrfmiddlewaretoken]').value;
    var stripe = Stripe("{{ STRIPE_PUBLIC_KEY }}");
    var checkoutButton = document.getElementById("checkout-button");
    checkoutButton.addEventListener("click", function () {
        fetch("{% url 'course:create-checkout-session' product.id %}", {
            method: "POST",
            headers: {
                'X-CSRFToken': csrftoken
            }
        })
            .then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({sessionId: session.id});
            })
            .then(function (result) {
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error("Error:", error);
            });
    });
</script>
</html>

templates/course/profile.html
{% extends "course/base.html" %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'profile.css' %}">
{% endblock %}
{% block content %}
    <div class="container mt-5">

        <div class="row d-flex justify-content-center">

            <div class="col-md-7">

                <div style="border-radius: 20px ;background-color: #F0F0F0; !important;" class="card p-3 py-4">

                    <div class="text-center">
                        <img style="border-radius: 20px" src="{{ user.image.url }}" width="100" >
                    </div>

                    <div class="text-center mt-3">
                        <span class="bg-secondary p-1 px-4 rounded text-white">Pro</span>
                        <h5 class="mt-2 mb-0">{{ user.username }}</h5>
                      {% if user.course_paid %}
                        <span>Active courses:</span>
                        {% for course in user.course_paid.all  %}
                          <li>{{ course.title }} <br>
{#                            All course lectures {{ course.lecture.count }} <br>#}
{#                          Your done lectures:#}
{#                          {{ number_done_lectures }}#}
                            {% endfor %}
                        </li>
                      {% endif %}

                        <div class="px-4 mt-1">
{#                            <p class="fonts">Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et#}
{#                                dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris#}
{#                                nisi ut aliquip ex ea commodo consequat. </p>#}

                        </div>

                        <ul class="social-list">
                            <li><i class="fa fa-facebook"></i></li>
                            <li><i class="fa fa-dribbble"></i></li>
                            <li><i class="fa fa-instagram"></i></li>
                            <li><i class="fa fa-linkedin"></i></li>
                            <li><i class="fa fa-google"></i></li>
                        </ul>

                        <div class="buttons">
                            <a href="{% url "course:profile-edit" pk=user.pk %}" class="btn btn-outline-primary px-4">Edit</a>
                            <button class="btn btn-primary px-4 ms-3">Learn</button>
                        </div>


                    </div>


                </div>

            </div>

        </div>

    </div>
{% endblock %}

templates/course/profile_update.html
{% extends "course/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-sm">
            </div>
            <div class="col-sm">
                <form action="" method="post" enctype="multipart/form-data">
                    <div class="form-group">
                        {% csrf_token %}

                        {{ form|crispy }}
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
            <div class="col-sm">
            </div>
        </div>
    </div>


{% endblock %}

templates/course/success.html
Success!